name: movie_app
description: Movie App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  bloc_concurrency: ^0.2.5
  get_it: ^7.7.0
  injectable: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.6.0
  pretty_dio_logger: ^1.4.0
  flutter_animate: ^4.5.0
  infinite_scroll_pagination: ^4.0.0
  collection: ^1.18.0
  retrofit: ^4.2.0
  retrofit_generator: ^8.2.0
  freezed_annotation: ^2.4.4
  sizer: ^3.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
